apiVersion: apps/v1
kind: Deployment
metadata:
  name: purchases-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: purchases
  template:
    metadata:
      labels:
        app: purchases
    spec:
      containers:
        - name: purchases
          image: mohcen/purchases
          imagePullPolicy: Always

---
apiVersion: v1
kind: Service
metadata:
  name: purchases-clusterip-srv
spec:
  selector:
    app: purchases
  type: ClusterIP
  ports:
    - name: purchases
      protocol: TCP
      port: 8002
      targetPort: 8002

---
apiVersion: v1
kind: Service
metadata:
  name: purchases-nodeport-srv
spec:
  type: NodePort
  selector:
    app: purchases
  ports:
    - name: purchases
      port: 8002
      targetPort: 8002
      protocol: TCP