apiVersion: apps/v1
kind: Deployment
metadata:
  name: validation-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: validation
  template:
    metadata:
      labels:
        app: validation
    spec:
      containers:
        - name: validation
          image: mohcen/validation
          imagePullPolicy: Always

---
apiVersion: v1
kind: Service
metadata:
  name: validation-clusterip-srv
spec:
  selector:
    app: validation
  type: ClusterIP
  ports:
    - name: validation
      protocol: TCP
      port: 8004
      targetPort: 8004

---
apiVersion: v1
kind: Service
metadata:
  name: validation-nodeport-srv
spec:
  type: NodePort
  selector:
    app: validation
  ports:
    - name: validation
      port: 8004
      targetPort: 8004
      protocol: TCP